%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%% Merge windows for windows matrix  %%%%%
%%%%%                   for Dentoo LT 4 %%%%%
%%%%%            written by T.Minagawa  %%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function out_vec = function_merge_window(win_matrix)
  out_vec = zeros((size(win_matrix,1)*size(win_matrix,2)./2)...
		  +ceil(size(win_matrix,1)/2),1);
  windows = hann(size(win_matrix,1));
  for i = 1 : size(win_matrix,2)
    out_vec = out_vec + ...
    vertcat(zeros(size(win_matrix,1)/2*(i-1),1),...
	    win_matrix(:,i).*windows,...
	    zeros(length(out_vec) - ...
		  (size(win_matrix,1)/2*(i-1)...
		  + size(win_matrix,1)),1));
  end;
end